### ISSUE TITLE
Latest version of code not published to npm

### ISSUE THREAD

**Issue by linuslagerhjelm** [moll/js-undersign#3]
It seems like the latest version of the code in this repository is not yet published on npm. Meaning that it is not possible to `nom install` it as that will basically only download the `README.md` file. This is a bit unfortunate as this looks like a cool project that I'd love to try out 😃

**Comment by moll** [comment]
Hey,

Yeah, sorry, I haven't gotten around to that. It should probably make do with some documentation as well. Having said that,  you should be able to install it straight from GitHub, too, for trying out. According to https://docs.npmjs.com/cli/v8/commands/npm-install/, the syntax is `npm install moll/js-undersign`.

**Comment by linuslagerhjelm** [comment]
That works indeed. I could submit a PR to update the installation docs with that command if you want?

**Comment by moll** [comment]
Glad to hear you got it installed. Thanks for the README offer, but I don't think it's necessary right now. There are a lot of tricks and tips with NPM one could utilize that are probably better explained in NPM's docs.
